version: '3.7'

services:
   api:
    build:
      context: ./docker/api/
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    environment:
      - DEMO_VAR=${DEMO_VAR}
 
  # database:
  #   image: mysql:5.7
  #   volumes:
  #     - assess_db:/var/lib/mysql
  #   environment:
  #     - "MYSQL_DATABASE=assess_db"
  #     - "MYSQL_ROOT_PASSWORD=secret"
  #   ports:
  #     - 33066:3306
# volumes:
#   assess_db: