version: '3.7'

services:
   api:
    build:
      context: ./dist/
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    environment:
      - KOOPEY_API_URL=${KOOPEY_API_URL}  
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}